name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to release, a bump type, or "auto"
        required: false
        default: auto
      merge_target:
        description: Target branch to merge into
        required: false
      force:
        description: Force a release even when there are release blockers
        required: false
        default: 'false'

permissions:
  actions: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: getsentry/craft@v2
        id: craft
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          version: ${{ inputs.version }}
          merge_target: ${{ inputs.merge_target }}
          force: ${{ inputs.force }}
          publish_repo: self

      - name: Trigger release CI
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_BRANCH: ${{ steps.craft.outputs.branch }}
        run: gh workflow run ci.yml --ref "$RELEASE_BRANCH"
